main: net.tfminecraft.nutrition.Nutrition
api-version: '1.21.10'
name: Nutrition
version: ${project.version}
author: Drefvelin

softdepend: [MMOItems, MythicLib]

commands:
  nutrition:
    description: View your current nutrition and diet variety
    usage: /nutrition